before_script:
  - apk update
  - apk upgrade
  - apk add bash
  - apk add openssh-client
  - apk add pytest

run-test:
  script:
    - pytest /builds/JuniPuff/dev-server/end-to-end/server-stuffs/server_stuffs/tests

update-server:
  only:
    - master@gitlab.squizzlezig.com/JuniPuff/dev-server
  script:
    - mkdir .ssh
    - chmod 700 .ssh
    - echo "$PRIV_KEY" | tr -d '\r' > .ssh/id_rsa
    - chmod 600 .ssh/id_rsa
    - bash ./thing.bash